# -*- coding: utf-8 -*-
"""Cópia de Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rI5t3MWRkMOzx7Ibkw7ePhvZBqOmZUxQ
"""

def calculadora():
    while True:
        print("\nEscolha uma operação:")
        print("1: Soma")
        print("2: Subtração")
        print("3: Multiplicação")
        print("4: Divisão")
        print("0: Sair")

        opcao = input("Insira o número para a operação correspondente: ")

        if opcao == '0':
            print("Saindo...")
            break
        elif opcao not in {'1', '2', '3', '4'}:
            print("Essa opção não existe")
            continue

        try:
            primeiro_valor = float(input("Digite o primeiro valor: "))
            segundo_valor = float(input("Digite o segundo valor: "))
        except ValueError:
            print("Por favor, insira valores numéricos válidos.")
            continue

        if opcao == '1':
            resultado = primeiro_valor + segundo_valor
            operacao = "Soma"
        elif opcao == '2':
            resultado = primeiro_valor - segundo_valor
            operacao = "Subtração"
        elif opcao == '3':
            resultado = primeiro_valor * segundo_valor
            operacao = "Multiplicação"
        elif opcao == '4':
            if segundo_valor == 0:
                print("Erro: Divisão por zero não é permitida. Por favor, escolha outros valores.")
                continue
            resultado = primeiro_valor / segundo_valor
            operacao = "Divisão"

        print(f"O resultado da {operacao} entre {primeiro_valor} e {segundo_valor} é: {resultado}")

if __name__ == "__main__":
    calculadora()